apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "one-app.fullname" . }}
  labels:
    {{- include "one-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "one-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "one-app.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "one-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: HOLOCRON_MODULE_MAP_URL
              value: {{ .Values.app.holocron_module_map_url }}
            - name: ONE_CLIENT_CDN_URL
              value: {{ .Values.app.one_client_cdn_url }}
            - name: ONE_CLIENT_REPORTING_URL
              value: {{ .Values.app.one_client_reporting_url }}
            - name: ONE_CLIENT_ROOT_MODULE_NAME
              value: {{ .Values.app.one_client_root_module }}
            - name: NODE_ENV
              value: production
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
